name: Generate Snake

on:
  schedule: # every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            "dist/github-snake-dark.svg?palette=github-dark"
            "dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"

      # Commit the files to the output branch
      - uses: actions/upload-artifact@v4
        with:
          name: snake-animations
          path: dist
